services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: onlinestore
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    container_name: mysqlserver
    # ports:             # Remove the port mapping to ensure the container is only accessible from the custom network
    #   - "3306:3306"     
    volumes:
      - data:/var/lib/mysql # Mount the volume to persist the data
      - ./mySql/init.sql:/docker-entrypoint-initdb.d/init.sql # Bind the init.sql file to the container
    networks:
      - my_custom_network  # Attach the custom network

  app:
    build: 
      context: ./appserver/
      dockerfile: Dockerfile
    # ports:
    #   - "8080:3000"
    container_name: appserver
    volumes:
      - ./appserver:/usr/src/appserver
      - /usr/src/appserver/node_modules # Prevents overwriting the container's node_modules
    depends_on:
      - mysql
    networks:
      - my_custom_network  # Attach the custom network
  

  web:
    build:
      context: ./webserver/
      dockerfile: Dockerfile
    container_name: webserver
    ports: 
      - "443:8080"
    networks:
      - my_custom_network

volumes:
  data:

networks:
  my_custom_network:       # Define the custom network
